### ISSUE TITLE
Request of improved implementation of Intelligent Room Controller (IRC)

### ISSUE THREAD

**Issue by tanker11** [JoDehli/PyLoxone#141]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen1

**Which software version does your loxone use?**

**How did you install HomeAssistant? Over Hassio oder manual install?**
Docker installation

**Which Version do you use of HomeAssistant?**
2022.11.2

PyLoxone version: 0.3.16

**Describe the bug**
This is not really a bug, but a missing feature of IRC under HA vial PyLoxone.
Under Loxone GUI (Web or App), if the user opens the settings of an IRC, there is an option for temperature override.
Once the temperature is defined, there is a time that defines when the override expires.
This is useful as the user does not forget the IRC in forced mode.

The request would be:
-implement the fixed temp override timing
-implement the tome of expiry as an entity attribute under the climate object
-status should show correctly that this option is selected (currently if the user activates in Loxone GUI, it is not shown under HA if this is a long term fixed temp or a timed override)

I do like this project and the developer is so professional that I hope this is something feasible.

Thanks!

**Comment by JoDehli** [comment]
@tanker11 

I think this is a good idea. I think I can make a seperate service for the override 
until a certain time. 

For know you can try to send a websocket comment with the following parameter:

id: the Id of the climate you want to override 
value: override/3/438375600/23.000000

The 438375600 is the time stamp in the future and the 23 is the temperature.

**Comment by JoDehli** [comment]
@tanker11 At the moment I will not make any further changes to the climate component because I have seen that it also works with HomeAssistant automations and helpers. 

I made you a small example to set the temperature and time for one or more climate controls. 

First you need the following helper: 


1. input_button for triggering the event
2. input_number for setting the desired temperature
3. input_date for setting the desired end time

Here a picture from my test: 

![image](https://user-images.githubusercontent.com/32484282/202860144-d46f558f-1e96-4982-8f03-0c349bbbc6c1.png)

On the gui in looks like this: 

![image](https://user-images.githubusercontent.com/32484282/202860118-0c760702-5f63-4743-a637-026e604973d0.png)

And of course the most important component is the automation.
Here is the automation yaml: 

```yaml
alias: test
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.taste_timmer
condition: []
action:
  - service: loxone.event_websocket_command
    data:
      value: >-
        override/3/{{ state_attr('input_datetime.zeit', 'timestamp') | int -
        1230768000 - 3600}}/23.000000
      uuid: 1a1cb29a-032c-c9c7-ffff403fb0c34b9e
mode: single
``

The only real dirty thing is that the timestamps of the loxone and the timestamp of HA are different. I do not know why loxone has a different timestamp. That means you must subtract 1230768000 from the timestamp you get from HA. It is the differenz from the normal epoch time to the loxone time which is the 1.1.2009. 

And for my time I must also subtract 1 hour which is the 3600.

I tried it and it worked perfect.

**Comment by tanker11** [comment]
Hello,

This is great, and totally fine.

Thanks!

Joachim D. ***@***.***> ezt írta (időpont: 2022. nov. 19.,
Szo, 17:20):

**Comment by JoDehli** [comment]
@tanker11 I thought about to make a extra service with only 3 paramete. Time, uuid or multiple uuids and temp. And do the time calculation internally this would be a good solution in my option.

**Comment by tanker11** [comment]
Indeed, this would help a lot in the implementation.
Thanks in advance, awesome work and focus on the integration!

Joachim D. ***@***.***> ezt írta (időpont: 2022. nov. 20., V,
11:46):
