### ISSUE TITLE
Please make an official HA integration 

### ISSUE THREAD

**Issue by somm15** [JoDehli/PyLoxone#23]
Hi !
I'm running your custom component for months now. It's great and stable.
Could you please make it an official HA integration?
Please Please Please Please Please Please Please Please :-)

**Comment by JoDehli** [comment]
First I have to remove all the websocket communication from the binding into a extra python module. Otherwise the home-assistant team will not accept it. This is a huge amout of work and I have not so much time at the moment. Sorry but I think with the hacs installation it is not so bad at the moment. Or why do you want a official integration? It is a lot more work for me to get it in the offical repo.

**Comment by somm15** [comment]
They are very strict with this lib/integration split. It's rather constraining (and annoying). 
I would prefer an official one to have more people using it :-)
I developed for Viessmann central heating. I developed the python lib and someone magically appeared and developed the HA integration. I've been very lucky.
The good point is that since it's used by an official component, people submit multiple PR for improvements each month.

**Comment by somm15** [comment]
By, the way, they are several deprecations since the last release (and I know, I should fix it, no highlight it).

**Comment by JoDehli** [comment]
I fixed it in the dev branch. I will make a new version soon.

**Comment by Juxz** [comment]
I don't know if it makes a huge difference in the amount of work, but it seems possible to develop a "HA integration" without being in HA core.

For instance, https://github.com/StyraHem/ShellyForHASS must be installed via HACS. It's not part of HA core. But still it's a damn good HA integration

**Comment by JoDehli** [comment]
I do not understand what you mean with "HA integration"? Is it not already a HA integration. It can be installed via Hacs as the Shelly. Do you mean with integration 
a automatic install? Of course this is easy. This should be possible. 

Of course the documentation is not really good but to be honest for me it is not really the important part as I can go in the source code an look up how it works. And I know a lot of special Loxone Features are missing. But I will maybe integrate some of the features but my main focus is that it works as long as I have a Loxone. And I hope my Loxone works the next view years. We have absolute no support and the documentation of the api is really really bad. So this is enough work for me. 

Why I not integrate all of the features? First I can not really test it because I have only some sensor and a view shutters. I have no lights or other hardware. And a other point that for some loxone entities there are no equivalent entity in HA. So there you must program a custom frontend entity. And I really do not want to do that.

And as I already mentioned for me it would only make sense to make a official HA integration for the core HA installation. I already started with a ha client. And when it is finished the complete communication is based of aiohttp as it is in HA. So it is a big change.

What you all can do for me is to improve the documentation. That would awesome. 
Maybe some examples with a loxone config picture and a Ha config from your configuration.

**Comment by Juxz** [comment]
Hi,

I spent more than one hour to find a proper "official" source to explain what I mean, but without any luck :( The best I could say to describe my previous message is :
- PyLoxone is installed with hacs and MUST be configured in configuration.yml. Once connected to Loxone Miniserver, it creates entities and scenes in HA and that's it.
- ShellyForHass is installed with hacs and can be configured in the GUI. It appears explicitly in the "Configuration/Integration" menu with a Shelly icon. All added/discovered Shelly items are visible in the "Configuration/Devices" menu, they can be added to Scripts, Scenes, Automations, Rooms. I can attach some screenshots if you'd like to see.

But I have no clue how difficult it is to move from one model to the other...

**Comment by JoDehli** [comment]
@Juxz I started the transformation to a custom_component which is configurable thru the UI. I think that is what you meant. You can try it from the dev branch.

**Comment by Juxz** [comment]
Will try asap!

**Comment by Juxz** [comment]
@JoDehli just tried the dev branch and this is brilliant!
This is why I meant in my previous messages. 
During this test, entities were not generated but the problem might be on my side, will check again later.

**Comment by JoDehli** [comment]
I know this problem. It is on the first start. Please try to restart HA then all supported entites should show up. I already think about a solution.
