### ISSUE TITLE
Dimmer min/max handling changes

### ISSUE THREAD

**Issue by arjenvrh** [JoDehli/PyLoxone#49]
I've updated to the latest version on Github and noticed that my dimmer is showing that it is turned on, even when it is off. The brightness is showing as close to half. 

In the LoxoneDimmer class, there are new statements handling the min/max values in the event_handler and brightness functions. 
When I disable these statements, as it was before, all seems to be working normally:

```python
    @property
    def brightness(self):
        """Return the brightness of the group lights."""
        return to_hass_level(self._position)

    async def event_handler(self, e):
        request_update = False
        if self._min_uuid in e.data:
            self._min = e.data[self._min_uuid]
            request_update = True

        if self._max_uuid in e.data:
            self._max = e.data[self._max_uuid]
            request_update = True

        if self._step_uuid in e.data:
            self._step = e.data[self._step_uuid]
            request_update = True

        if self.states['position'] in e.data and isinstance(e.data[self.states['position']], (int, float)):
            self._position = e.data[self.states['position']]
            request_update = True

        if request_update:
            self.async_schedule_update_ha_state()
```

Is there a reason why the min/max values need to be mapped in code? It seems that the position values from Loxone already are being mapped to the Loxone range. My min and max values are 15 and 100, in home assistant the brightness is showing as 1-100. In the Loxone App the brightness values now correspond directly to the brightness values in HA. 

Regards

**Comment by JoDehli** [comment]
Can give me more information about the dimmer or the light controller configuration?

**Comment by arjenvrh** [comment]
I'm using the dimmer control, not the light controller. A nano touch is used to control a dimmer air, configured as outlined in the screenshots below:
![cfg2](https://user-images.githubusercontent.com/29952434/107192998-a10c4180-69ee-11eb-9f38-5d6bad9028e2.png)
![cfg1](https://user-images.githubusercontent.com/29952434/107193108-c4cf8780-69ee-11eb-8185-daeeb605918f.png)

**Comment by JoDehli** [comment]
@arjenvrh I started with a new interpolation function for your problem. But I had no time to finish. Sorry. Maybe this weekend ;-)

**Comment by JoDehli** [comment]
@arjenvrh I tried to fix it without screw something else up. :-) The problem is that the light controller uses the dimmer component differently. Maybe you can test again the dev branch. I have no light so I always try it on some fake devices which I create.

**Comment by johny-mnemonic** [comment]
I am afraid your blind shot didn't succeed.
I just updated to the latest release, as without it light control was not working at all thanks to the [missing attribute for light switch](https://github.com/JoDehli/PyLoxone/commit/bf8461fd3aebf8fae16c1a51422afa064aad5ef6). This fixed it for regular lights, but something is still broken for more complex lights (RGB/RGBW in my case).
When I turn-on the light, nothing visibly happens with the light (it doesn't light up), but that could be expected. Then I can select color and it light's up. But then when I turn-off the light, HA shows the light as turned-off, but Loxone shows it as having "main brightness" of whole light controller at 100%, while the brightness of the light at 0%.

**Comment by JoDehli** [comment]
@johny-mnemonic sorry but I really can not reproduce your errors. It is the biggest problem that I can only test the software on my machine. All my test lights (as I already mentioned I have no lights installed) work perfectly. No errors at all. I can switch, change brightness and color. All works perfect. I do not know how to help sorry.

**Comment by johny-mnemonic** [comment]
@JoDehli I remember, that you mentioned you have no lights connected to Loxone, but now you mention that your test lights works, so I am a bit confused.

Anyway. Is there anything I can try to help you (debug output, some sequence of actions)?

Basically the issue is, that there is no way to turn-off the light from HA completely as that main brightness slider stays at last set value and we have no control over it from HA.

I just played with it a bit and found that there is no way to decrease the brightness in HA to 0. It only goes to 1 as a lowest value.

I have also found, that this issues is limited to RGB light only. Simple dimmable light works as expected. It remembers the last brightness value before you turned it off, so when you turn it on again it goes right to the last used value. RGB light always go to 1% no matter what brightness was set before turning it off.

So for example when the light is turned-off, you can turn it on by sliding the brightness slider from zero and this way it shines right away (instead of only going to 1% after you turn it on by the switch). 
In Loxone the light block has main brightness at the highest brightness you set for the RGB output from HA. It increases when you increase the brightness from HA, but it does not ever decrease when you decrease brightness from HA. Only the RGB output brightness decreases. 
This behavior is consistent with what happens when I only play with the RGB brightness slider in Loxone (it only increases the main block brightness, but never decreases it).
When you then turn-off the light from HA the RGB output brightness is brought down to 0%, but main brightness stays on the current value.
When the light is on, there are then three ways to turn whole light block off:
1) slide the RGB slider to 0% (which is not possible from HA now)
2) slide the main slider to 0% (also not possible from HA)
3) activate "turned-off" scene (I noticed only now that my scenes vanished from HA as I almost don't use them)

I also noticed there is no switch in Loxone to switch the dimmable lights off, that would correspond to the switch available in HA. In case you are calling the same action as for the simple lights (that do have the switch in Loxone) this might be the root cause of these troubles.
No matter how you implement that switch it looks like what you do is confusing Loxone:
I now tried to use that switch in HA to turn the light off and then back on (it stayed ON from Loxone point of view) and since I did that I can't bring the light to OFF state by sliding the RGB brightness to 0% in Loxone. Only main brightness or the "turn off" scene now turns the whole light block off. 
So the Loxone is obviously confused byt the command it gets from HA. Luckily turning that block off in Loxone fixes it.

Maybe it is important to say, that all blocks where I see this behavior have at least three light outputs, not just a single one. I am not sure if that can make any difference as I have no room where I have only the single RBG light to compare.

**Comment by JoDehli** [comment]
@johny-mnemonic maybe we should try it direct by mail here is my mail address joachim.dehli@gmail.com
